
# Ansible/docker guide:
# https://docs.ansible.com/ansible/latest/collections/community/docker/docsite/scenario_guide.html
---

- name: Import home assistant playbook
  import_playbook: homeassistant.yml

- name: Import Wireguard playbook
  import_playbook: wireguard.yml

- name: Import dns_update playbook
  import_playbook: dns_update.yml

# - name: Import vsftp playbook
#   import_playbook: vsftp.yml

- name: Import jellyfin playbook
  import_playbook: jellyfin.yml

- name: Import rclone playbook
  import_playbook: rclone.yml
